title: Universal-init.d
description: A simple Android application which emulates the behavior of the init.d kernel mechanism (automatic execution of the scripts contained within the /system/etc/init.d folder at each boot)
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
